assets/static/style.css
content/cclogo.svg
templates/layout.html
templates/project-ideas-page.html

Improved Google Summer of Code ideas page

---

content/gsoc-2019/project-ideas-collection/automated-link-checking/contents.lr

added automated link checking

---

content/community/contents.lr

Just a PR to add some useful content to the **community** endpoint. Content consists of info about joining channels and etiquette on Slack. Feel free to propose changes.

Added info about joining channels and etiquette on Slack

---

templates/layout.html

The website is already responsive. It just does not scale on mobile phone as it should. Adding a meta viewport will fix it.

Responsiveness

---

.github/issue_template.md
.github/pull_request_template.md

Closes #XXXXX
Added templates for creating PRs and issues on the repo. If there is another standard to be followed, do let me know!

Created PR and issue templates

---

content/contents.lr

Closes #XXXXX
* reqiest -> request

Fixed spelling

---

.github/pull_request_template.md
CODE_OF_CONDUCT.md

Added Code of Conduct, updated PR template with DCO.

---

templates/project_list.html

👍 I was just checking the recently updated projects page, and the featured projects are looking good! Just wanted to submit this quick spelling fix:
* tha -> the
Closes #XX
**Checklist**  
Version 1.1
Suite D4700
of my …

Spelling fix

---

.github/CODEOWNERS
CODE_OF_CONDUCT.md
CONTRIBUTING.md

**Checklist**  
Version 1.1
Suite D4700
work with modifications, whether created in whole or in part …

Adding codeowners file and contribution guidelines.

---

content/gsoc-2019/project-ideas-collection/search-by-use-case/contents.lr

Updated the Search by use case project idea with some more details on what could be done. Also updated the primary mentor to be Alden, since I believe most of the work will be on the API, which drives the search results, and not so much on the frontend.

Update Search by use case GSoC idea description

---

assets/static/style.css

Fixes #11 
Removed height attribute from footer class to fix above issue.
**Checklist**
Version 1.1
Suite D4700
license and I have the right under …

Fixed: Overflowing text and whitespace in footer

---

content/contributing-code/contents.lr

Added list of browsers required to be supported to code guidelines.
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Added list of browsers required to be supported to code guidelines.

---

templates/macros/pagination.html

Fixes #50 
Changed the pagination macro to show links to all the pages and improve the design. 
Please refer to the screenshot below.
Please tell me if any change in UI is needed.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
have the right to submit …

 change pagination macro to add styles to show all pages of Blog

---

content/contributing-code/contents.lr
content/gsoc-2019/contents.lr

Added proposal review guidelines and pull request turnaround expectations.
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Content updates

---

templates/blog-post.html

Fixes #64 
This updates the blog date format to the same order as ISO 8601 format
**Checklist:**
- [ x ] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [ x ] My pull request targets the `master` branch of the repository.
- [ x ] My commit messages follow [best practices][best_practices].
- [ x ] I added tests for the changes I made (if applicable).
- [ x ] I added or updated documentation (if applicable).
- [ x ] I tried running the project locally and verified that there are no
Version 1.1
Suite …

Updates blog date format

---

content/gsoc-2019/contents.lr

Fixes #63 
Add more information about mentor availability, project slots, and proposal selection criteria to the GSoC 2019 "General Information" page.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
have the right to submit it under the open source …

Add more information regarding proposal selection, and mentor availability to GSoC "General Information" page.

---

templates/macros/pagination.html

Fixes #69 
Added class = "table-responsive" in Pagination to make it responsive in smaller devices
Version 1.1
Suite D4700
license and I have the …

Added Table Responsive in Pagination

---

content/blog/authors/TimidRobot/contents.lr
content/blog/authors/contents.lr
content/blog/categories/SaltStack/contents.lr
content/blog/categories/community/contents.lr
content/blog/categories/contents.lr
content/blog/categories/open-source/contents.lr
content/blog/contents.lr
content/blog/entries/contents.lr
content/blog/entries/open-development-with-saltstack/contents.lr
templates/layout.html

Created a new blog, linked it from the top navigation, and published @TimidRobot's post.
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Set up CC Open Source blog and first post.

---

content/blog/authors/akmadian/contents.lr
content/blog/entries/cc-chooser-week2/contents.lr

This is my blog post for week  2 of GSoC :) I closed the old PR and opened this one cause it would be cleaner. I think I got everything @kgodey 
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Add GSoC blog post - Week 2

---

content/blog/entries/cc-chooser-week4/contents.lr

Adds my blog post for GSoC Week 4.
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Add Week 4 Blog Post

---

content/blog/entries/cc-browser-extension-a-gsoc-project/contents.lr
content/blog/entries/cc-browser-extension-week5-6/contents.lr

Adds blog post titled CC Browser Extension Week 5, 6
**Checklist:**
index.md`).
Version 1.1
Suite D4700
of my knowledge, …

Add blog post: CC Browser Extension Week 5, 6 and fix link in previous post

---

content/blog/authors/bhumijgupta/contents.lr
content/blog/categories/cc-link-checker/contents.lr
content/blog/entries/cc-link-checker/contents.lr

Added blog post for cc-link-checker
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Added cc-link-checker blog post

---

content/blog/entries/saltstack-host-classification/contents.lr

Fixes #XX
Adds Host Classification with SaltStack blog post
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

added saltstack-host-classification post

---

content/blog/authors/bhumijgupta/contents.lr
webpack/package-lock.json

Added md5 email hash and about info about myself
**Checklist:**
index.md`).
Version 1.1
Suite D4700
of my …

Added author info

---

content/blog/entries/cc-browser-extension-week9-10/contents.lr

Add blog post titled: CC Browser Extension Week 9, 10
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Add blog post: CC Browser Extension Week 9, 10

---

content/blog/entries/cc-chooser-lastweek/contents.lr

This PR adds the last blog post for the cc-chooser project
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Add last blog post for GSoC cc-chooser

---

content/blog/authors/akmadian/contents.lr

Since I wrote my original bio, I've turned one year older, and my taste in tea changed :) (among other things) This PR updates my author page to reflect that.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
have the right to submit …

Update akmadian author page

---

content/community/contents.lr

This tag leads Outreachy applicants to the Slack channel dedicated to CC project contributions.
Fixes #XX
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Add #cc-gsoc-outreachy tag

---

content/contributing-code/contents.lr

Fixes #123 
Fixed a typo in the contributing code page
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Fixed a typo in the contributing code page

---

content/programs/outreachy/2019-12-start/contents.lr

This PR aims to emphasize to potential Outreachy applicants that not all the proposed projects will be funded. 
**Checklist:**
- [ x ] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [ x ] My pull request targets the `master` branch of the repository.
- [ x ] My commit messages follow [best practices][best_practices].
- [ x ] I tried running the project locally and verified that there are no
Version 1.1
Suite D4700
license …

highlighting the number of accepted interns for outreachy

---

content/programs/outreachy/2019-12-start/contents.lr

Added a link to the [Outreachy proposal template](https://docs.google.com/document/d/1qJF51MNk2KD_A0g3e3LRFmK-p5DD4owg7lXByjQWclM/edit) in the relevant section.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
have the right to submit it under the open …

Add a link to the Outreachy proposal template

---

templates/layout.html

Added link to creativecommons.org in the main navigation.
Fixes #103 
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Updated main navigation

---

content/blog/categories/tech/contents.lr
content/blog/entries/ssr-ccsearch/contents.lr

Blog post about Server Side Rendering with VueJS on CC Search

CC Search SSR blog post

---

content/blog/entries/ssr-ccsearch/contents.lr

**Checklist:**
index.md`).
Version 1.1
Suite D4700
license …

Updated published date.

---

content/blog/authors/akmadian/contents.lr

Fixes #XX
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

akmadian author page - Change tea tastes :)

---

content/blog/entries/2019-11-25-empowering-collaboration/contents.lr

Added Empowering Collaboration in the Commons blog post
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …

Empowering collaboration blog post

---

content/blog/authors/apdsrocha/contents.lr
content/blog/entries/cc-platform-toolkit-revamp/contents.lr

Add author page for Ana Rocha;
Add post referring to first 2 weeks of working on revamping the platform toolkit
- [ x ] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [ x ] My pull request targets the `master` branch of the repository.
- [ x ] My commit messages follow [best practices][best_practices].
- [ NA ] I added tests for the changes I made (if applicable).
- [ NA ] I added or updated documentation (if applicable).
- [ x ] I tried running the project locally and verified that there are no
```
Version 1.1
Suite D4700
San …
```

Add Outreachy post - CC Platform Toolkit Revamp

---

templates/layout.html
webpack/sass/main.scss

Fixes #146
Fixed the poor mobile readability and also made it mobile-responsive and changed the text alignment to justify.
**Before**
**After**
index.md`).
```
Version 1.1
Suite D4700
(b) …
```

Fixing poor mobile readability and text alignment

---

content/blog/entries/cc-browser-extension-a-gsoc-project/contents.lr
content/blog/entries/cc-browser-extension-week5-6/contents.lr
content/blog/entries/cc-browser-extension-week7-8/contents.lr
content/blog/entries/cc-browser-extension-week9-10/contents.lr
content/blog/entries/cc-chooser-lastweek/contents.lr
content/blog/entries/cc-chooser-week2/contents.lr
content/blog/entries/cc-chooser-week4/contents.lr
content/blog/entries/cc-datacatalog-data-processing-2/contents.lr
content/blog/entries/cc-datacatalog-data-processing-3/contents.lr
content/blog/entries/cc-datacatalog-data-processing/contents.lr
content/blog/entries/cc-datacatalog-data-thelinkedcommons/contents.lr
content/blog/entries/cc-datacatalog-visualization/contents.lr
content/blog/entries/cc-vocabulary-new-design-system/contents.lr
content/blog/entries/cc-vocabulary-so-far/contents.lr
content/blog/entries/cc-vocabulary-the-main-course/contents.lr
content/blog/entries/cc-wp-plugin-final-phase/contents.lr
content/blog/entries/cc-wp-plugin-first-phase/contents.lr
content/blog/entries/cc-wp-plugin-second-phase/contents.lr
content/blog/entries/introducing-cc-search-extension/contents.lr
content/blog/entries/vocabulary-so-long/contents.lr
content/blog/series/gsoc-2019-browser-extension/contents.lr
content/blog/series/gsoc-2019-chooser/contents.lr
content/blog/series/gsoc-2019-dataviz/contents.lr
content/blog/series/gsoc-2019-vocabulary/contents.lr
content/blog/series/gsoc-2019-wp-plugin/contents.lr
content/community/write-a-blog-post/contents.lr
templates/blog-post.html
templates/blog-series.html

New style:
index.md`).
```
Version 1.1
Suite D4700
license …
```

Add blog series to GSoC posts, change style & display of blog series

---

content/blog/entries/cc-platform-toolkit-revamp-2/contents.lr

I've added my second blog post updating on the progress of my Outreachy project.
- [ x ] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [ x ] My pull request targets the `master` branch of the repository.
- [ x ] My commit messages follow [best practices][best_practices].
- [ x ] I tried running the project locally and verified that there are no
```
Version 1.1
Suite D4700
Developer's …
```

add 2nd blog post on platform toolkit revamp

---

content/blog/authors/conye/contents.lr
content/blog/entries/cc-vocabulary-my-first-four-weeks/contents.lr
content/blog/series/outreachy-dec-2019-vocabulary/contents.lr

This is my first blog post on Extending the Scope/Usage of CC Vocabulary - Outreachy project.
index.md`).
```
Version 1.1
Suite D4700 …
```

First Blog Post - Extending the Usage of CC Vocabulary

---

content/blog/authors/mathemancer/contents.lr
content/blog/categories/airflow/contents.lr
content/blog/categories/testing/contents.lr
content/blog/entries/apache-airflow-testing-with-pytest/contents.lr

This post is about some challenges encountered, and tricks to get around them when testing Apache Airflow DAGs (Directed Acyclic Graphs) with `pytest`.
index.md`).
```
Version 1.1
Suite D4700
indicated in the file; …
```

add airflow testing blog post

---

content/internships/project-ideas-collection/cc-search-accessibility/contents.lr

Fixes #XX
index.md`).
```
Version 1.1
Suite D4700
license and …
```

Remove Kriti, add Ari as mentor to cc-search-accessibility

---

templates/layout.html

Fixes #172 
This changes the text of the tab on https://opensource.creativecommons.org/ from 'cc.org' to 'creativecommons.org'  (cc.org is the website of Christian Coalition, not associated with Creative Commons)
I'm (extremely) open to suggestions for better text than what I changed it to
index.md`).
```
Version 1.1
Suite D4700
(a) The …
```

change text of tab linking to main CC page

---

content/internships/project-ideas-collection/add-audio/contents.lr

Reduces the scope of the audio outreachy/GSoC project .
index.md`).
```
Version 1.1
Suite D4700 …
```

Shrink the audio intern project

---

content/contributing-code/github-repo-guidelines/contents.lr

index.md`).
```
Version 1.1
Suite D4700 …
```

Updated GitHub repo guidelines to reflect new public repo.

---

content/internships/project-ideas-collection/catalog-expansion/contents.lr
content/internships/project-ideas-collection/linked-commons/contents.lr
content/internships/project-ideas-collection/metrics-dashboard/contents.lr
content/internships/project-ideas-collection/web-monetization/contents.lr

Fixes #176 
Replaces Low --> Easy, High --> Hard in all the relevant ideas.
index.md`).
```
Version 1.1
Suite D4700
of my …
```

Categorize ideas as per page difficulty levels

---

content/community/contents.lr
content/internships/applicant-guide/contents.lr
content/internships/contents.lr

index.md`).
```
Version 1.1
Suite D4700 …
```

Added mentor information, some other minor content changes.

---

content/internships/contents.lr

index.md`).
```
Version 1.1
Suite D4700 …
```

Added GSoC organization page and participation info.

---

content/community/contents.lr

- Added CC Search channel
- Alphabetized channels in table
- Removed line about CC engineers all being in the Americas (not true any more!)
index.md`).
```
Version 1.1
Suite D4700
(b) The …
```

Updated community page documentation

---

content/community/contents.lr

Add new channel as requested by @kgodey on slack.
Also fix writing style for others.
index.md`).
```
Version 1.1
Suite D4700 …
```

Add #cc-dev-legal-database channel to Community page

---

content/contributing-code/contents.lr
content/internships/applicant-guide/contents.lr

- Simplified code contribution guidelines 
- Added link to project proposal template
- Clarified application guidelines
index.md`).
```
Version 1.1
Suite D4700 …
```

Updated code guidelines & added project proposal template

---

webpack/sass/main.scss

Fixes #182 
Added property z-index to CSS of #back-to-top button to fix the bug which caused the button to stop working on small screens when user reached footer. 
index.md`).
```
Version 1.1
Suite D4700
indicated …
```

Change z-index of #back-to-top button

---

templates/layout.html

Fixes #100 
Added Image preview feature so that it looks good while sharing the links.
This PR has the only implementation of the image preview.
index.md`).
```
Version 1.1
Suite D4700
(b) …
```

Added Image preview options for social media sharing

---

content/blog/entries/cc-platform-toolkit-revamp-4/contents.lr

Adding final blog post about the platform toolkit revamp project, part of the Outreachy program, 2019-2020 round.
index.md`).
```
Version 1.1
Suite D4700 …
```

add blog post #4 about platform toolkit revamp

---

content/contributing-code/contents.lr
content/contributing-code/pr-guidelines/contents.lr

index.md`).
```
Version 1.1
Suite D4700 …
```

Updated contribution and PR guidelines; removed issue assignment step.

---

content/blog/entries/2020-03-05-participe-gsoc/contents.lr

Blog post about GSoC and Outreachy in Portuguese
```
Version 1.1
Suite D4700
work with modifications, …
```

GSoC/Outreachy blog post in PT

---

content/blog/entries/2020-03-05-involucrate-gsoc-outreachy-es/contents.lr

Blog post about GSoC and Outreachy in Spanish
index.md`).
```
Version 1.1
Suite D4700
of my knowledge, is covered under an …
```

Blog post GSoC/Outreachy in Spanish

---

content/community/contents.lr

Fix misspelling in line 68 of the community page
Fixes #198
Fixed a misspelling on line 68 of 
page https://opensource.creativecommons.org/community
index.md`).
```
Version 1.1
Suite D4700 …
```

Fix bug - misspelling

---

templates/layout.html

- Created a new branch 'github-icon-issue'
- Moved Lines 31-32 to 109-110
Fixes #191 
Github Repository icon hides behind the CC icon.
- Moved Lines 31-32 to 109-110
This will make the Github Repository icon to be above the CC icon.
CC icon is big so it is also clickable.
index.md`).
```
Version 1.1
Suite D4700
(a) The contribution was …
```

Fixed issue #191 - Github repo icon not clickable on mobile devices

---

.github/workflows/lektor-build-deploy.yml

Fixes #48 
Added workflow file to move continuous deployment to github actions.
index.md`).
```
Version 1.1
Suite D4700
of …
```

move continuous deployement to github actions for CC opensource website

---

.github/workflows/lektor-build-deploy.yml

Fixes #48 
- Added username and password to GitHub repo secrets and Lektor deploy command
- Set up deployment so that it only runs on pushes to `master` (build should run on all pushes).
index.md`).
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```

Fixes for GitHub Action to build and deploy the site.

---

.github/workflows/lektor-build-deploy.yml

Fixes #48 
index.md`).
```
Version 1.1
Suite D4700
license …
```

Fixed reference to master in deployment

---

content/internships/project-ideas-collection/legal-database/contents.lr

index.md`).
```
Version 1.1
Suite D4700 …
```

Removed Sarah from list of mentors

---

content/contributing-code/cc-search/contents.lr
templates/layout.html

Fixes https://github.com/creativecommons/cccatalog-frontend/issues/407 (long overdue)
Adds this page:
index.md`).
```
Version 1.1
Suite D4700 …
```

Added CC Search feature contribution guide.

---

.github/workflows/lektor-build-deploy.yml

The build workflow wasn't running on PRs. I fixed it.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Build site on PRs as well

---

content/blog/entries/cc-vocabulary-week9-13/contents.lr

My third blog post
index.md`).
<details>
```
Version 1.1
Suite D4700
of …
```

Added my third blog post

---

.lektorproject
templates/layout.html

Fixes #184 by @techievivek 
Added description content for meta tags for better social share.
Added [markdown-excerpt](https://www.getlektor.com/plugins/lektor-markdown-excerpt/) Lektor plugin to achieve this. Also in some page **body** part was missing so I extracted content from **description** part.
View the source code of any page and try to see `meta description tag`
index.md`).
<details>
```
Version 1.1
Suite D4700
license …
```

added description content for meta description

---

webpack/package-lock.json
webpack/package.json

```
npm WARN babel-loader@8.0.6 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```
```
found 214 low severity vulnerabilities in 6305 scanned packages
```
Resolve npm issues
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) …
```

resolve babel version issue and various security issues

---

README.md

Updated README
- we use GitHub Actions now
- improved formatting
- minor updates for improved clarity
- included GitHub organization name (creativecommons/creativecommons.github.io ) so that creativecommons.github.io isn't mistaken for a domain name
old README rendered: [`master/README.md`](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/README.md)
new README rendered: [`readme-updates/README.md`](https://github.com/creativecommons/creativecommons.github.io-source/blob/readme-updates/README.md)
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```

Minor README updates to improve clarity and readability

---

.lektorproject
README.md

Organized and documented Lektor plugins:
1. sorted plugins
2. added links to README for plugins in use
- (see rendered [lektor-plugins/README.md#lektor-plugins](https://github.com/creativecommons/creativecommons.github.io-source/blob/lektor-plugins/README.md#lektor-plugins))
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```

Organized and documented Lektor plugins

---

content/blog/entries/2020-04-03-nvmee-on-debian-on-aws/contents.lr

new blog post: NVMEe on Debian on AWS blog
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

new blog post: NVMEe on Debian on AWS blog

---

README.md

Added Code of Conduct and Contributing sections to README
(I was inspired by the [Authors](https://github.com/creativecommons/cccatalog/blob/master/README.md#authors) section of the cccatalog README)
Rendered READMEs:
- [Current (`master` branch)](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/README.md)
- [Proposed (`moar-readme-updates` branch)](https://github.com/creativecommons/creativecommons.github.io-source/blob/moar-readme-updates/README.md)
index.md`).
- N/A I added tests for the changes I made (if applicable).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The …
```

Added Code of Conduct and Contributing sections to README

---

content/internships/contents.lr
content/internships/history/contents.lr
templates/layout.html

- Moved "History" section into its own page.
- Reorganized "Overview" Page to be shorter and explain things a bit better.
- Added Google Season of Docs to "Overview" page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Internship program content updates

---

README.md

Fixes #231
- added license details for content and font awesome
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

added license details for content and font awesome

---

content/community/community-teams/contents.lr

Fixes #237 by @akmadian 
Originally the issue corresponded to an improper indentation in a section of the page. But, a few more bugs related to styling were identified by me and I have brought them to notice in the original issue itself. This PR removes all the mentioned bugs as shown in the Screenshots section below.  
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Correct bugs in Community Team page

---

content/internships/contents.lr

index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Updated Google Season of Docs status.

---

content/blog/entries/date-partitioned-data-reingestion/contents.lr

This PR adds a blog post about our strategy for reingesting data to CC Catalog over time.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```

Add blog post about metadata reingestion strategy

---

content/internships/applicant-guide/contents.lr

This PR includes changes to the language in the internship applicant guide page to make the content more GSoD friendly. These changes include updates to the proposal evaluation criteria and clarification of how to contribute documentation, as well as little bits and pieces here and there to be more inclusive of GSoD.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Make internship applicant guide GSoD friendly

---

README.md

Fixes #252  by @rajat2502 
Fixes a grammatical mistake in the README
index.md`).

Fixes grammatical error in the README

---

content/blog/entries/improving-cc-license-chooser-outcomes/contents.lr

Fixes #[issue number] by @[issue author]
Add blog post about the outcomes of my Outreachy internship.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in …
```

Olga Bulat's Outreachy Internship post

---

content/community/community-team/contents.lr

- Added project maintainers
- Changed application requirements to guidelines
- Changed required number of contributions
- Formatting changes
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```

Added project maintainer and made some content changes.

---

content/community/contents.lr

Fixes #270 by @krysal
Added new entry of `cc-dev-catalog` for CC Catalog in table.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```

Added the correct slack channel for CC Catalog

---

content/community/community-team/project-roles/contents.lr
templates/layout.html

index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Added project maintainer guidelines.

---

content/community/community-team/project-roles/contents.lr

index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Content updates based on review.

---

content/blog/authors/makkoncept/contents.lr
content/blog/entries/cc-browser-extension-upcoming-improvements/contents.lr

This PR: 
- fixes a typo in blog post `Upcoming improvements/features in CC Search Extension`.
- Updates author bio of Mayank Nader.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```

Fixed typo in Browser extension upcoming improvements post and update bio

---

content/blog/entries/resource-gathering/contents.lr

This PR updates the publication date on this post
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update publication date on blog post

---

databags/community_team_members.json
templates/community_team_list.html

This PR adds support for community roles and updates the community team list databag.
There should be a corresponding pr in `ccos-scripts`, the databag was modified manually for now.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part …
```

[Re]- Add community role support, update databag

---

content/archives/old-tech-blog/entries/the-easiest-way-yet-to-integrate-cc-licensing/contents.lr
content/blog/entries/2019-09-11-google-docs-plugin/contents.lr

Fixes #284 by @TimidRobot 
Updates the links to remove mixed content error produced by netlify.
Replace `http` with `https` for the specified links.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to …
```

Fix mixed content error

---

webpack/package-lock.json
webpack/package.json
webpack/sass/main.scss

Updates vocabulary version and imports tokens in the scss file.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update vocabulary version.

---

.github/CODEOWNERS

<details>
```
Version 1.1
Suite D4700
work with …
```

Updated CODEOWNERS to all of engineering

---

content/contents.lr
content/contributing-code/usability/contents.lr
templates/layout.html

Fixes #267  by @annatuma 
This adds a new page `Usability` as discussed in the issue.
PS- The links won't open in a new tab/window as markdown doesn't support this. Probably plain HTML would have to be used to achieve this.
```
<a href="www.example.com" target="_blank">link text</a>
```
index.md`).
<details>
```
Version 1.1
Suite D4700
By …
```

Usability page

---

webpack/sass/main.scss

This adds styling for the links of the website which is forest-green color.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Update link styling for whole website

---

themes/vocabulary_theme/templates/layout.html
webpack/js/main.js
webpack/package-lock.json
webpack/package.json

Updates footer using the new version of Vocabulary.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update footer according to the new version of vocabulary

---

templates/search_roadmap.html

Fixes #268 by @annatuma 
Linked the recently added Usability page from CC Search page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Added link to Usability page from CC Search page

---

content/blog/authors/brenoferreira/contents.lr
content/internships/contents.lr

<details>
```
Version 1.1
Suite D4700
work with …
```

Updated Breno's bio and mentor list.

---

content/blog/authors/dhruvkb/contents.lr

This PR updates my bio.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update bio to reflect the changes over the year

---

themes/vocabulary_theme/templates/blog-post.html
themes/vocabulary_theme/templates/layout.html
webpack/sass/main.scss

This updates single post page as per the mockups.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update single-entry page

---

themes/vocabulary_theme/templates/blog-series-list.html
themes/vocabulary_theme/templates/macros/series.html
webpack/sass/main.scss

This updates all series page. Path for the page - `http://localhost:5000/blog/series/`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

update all series page

---

themes/vocabulary_theme/templates/blog-categories.html
themes/vocabulary_theme/templates/macros/categories.html
webpack/sass/main.scss

This PR updates all-categories page.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```

update all categories page

---

content/contents.lr
flowblocks/featured-projects.ini
models/home.ini
themes/vocabulary_theme/templates/blocks/featured-projects.html
webpack/sass/main.scss

Adds `Featured projects` section to the home page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Add featured projects section to home page.

---

content/contributing-code/github-repo-guidelines/contents.lr
content/contributing-code/pr-guidelines/contents.lr
webpack/sass/main.scss

Updates PR guidelines page.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
```

Update PR guideline page

---

themes/vocabulary_theme/templates/author.html
themes/vocabulary_theme/templates/macros/author_posts.html
webpack/sass/main.scss

Updates the author posts page. Check updates on path - `/blog/authors/ahmadbilaldev/`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update author posts page

---

content/contributing-code/github-repo-guidelines/contents.lr
content/contributing-code/pr-guidelines/contents.lr
themes/vocabulary_theme/templates/author.html
themes/vocabulary_theme/templates/blog-series.html
themes/vocabulary_theme/templates/macros/author_posts.html
webpack/sass/main.scss

This updates a series posts page. Here is the path - `/blog/series/gsoc-2019-browser-extension/`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update series posts page.

---

content/community/code-of-conduct/contents.lr
content/community/community-team/community-building-roles/contents.lr
content/community/community-team/contents.lr
content/community/community-team/project-roles/contents.lr
content/community/contents.lr
content/community/write-a-blog-post/contents.lr
themes/vocabulary_theme/templates/page-with-toc.html

This updates pages under /community according to mock-ups.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update '/community' pages according to mockup

---

themes/vocabulary_theme/templates/blog-category.html

This updates category's posts page. Here is the path - `/blog/categories/cc-catalog/`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update category posts.

---

content/contributing-code/cc-search/contents.lr
themes/vocabulary_theme/templates/cc-search-guide.html
webpack/sass/main.scss

This updates guidelines to CC search feature page. `/contributing-code/cc-search`
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```

Update ccsearch page.

---

.github/CODEOWNERS

<details>
```
Version 1.1
Suite D4700
work with …
```

Updated CODEOWNERS with collaborators

---

themes/vocabulary_theme/templates/project_list.html
webpack/sass/main.scss

Update project list page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update project list page.

---

content/internships/applicant-guide/contents.lr
content/internships/contents.lr
content/internships/intern-guide/contents.lr
content/internships/mentor-guide/contents.lr
themes/vocabulary_theme/templates/page-with-toc.html

This updates pages under `/internships` section.
This updates - 
1. /internships/applicant-guide/
2. /internships/intern-guide/
3. /internships/mentor-guide/
4. /internships/history/
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part …
```

Update intern guide pages.

---

webpack/package-lock.json
webpack/package.json

Updates vocabulary version to the latest.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update vocabulary version

---

themes/vocabulary_theme/templates/community_team_list.html
webpack/sass/main.scss

This updates Community Team members page. Path - `/community/community-team/members/`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update team members page

---

themes/vocabulary_theme/templates/macros/pagination.html

As per new version of the vocabulary, this PR adds previous and next to the pagination component.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Add previous and next to pagination.

---

themes/vocabulary_theme/templates/search_roadmap.html
webpack/sass/main.scss

This updates the CC Search roadmap page. Path - `/cc-search/`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update ccsearch roadmap page.

---

themes/vocabulary_theme/templates/project-ideas.html
themes/vocabulary_theme/templates/project_list.html
webpack/sass/main.scss

This updates project ideas page.` /internships/project-ideas/`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

update project ideas page

---

webpack/package-lock.json
webpack/package.json
webpack/sass/main.scss

This fixes current import issues.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

fix import issue

---

content/contents.lr

Fixes the hero section's button color.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```

Fix hero section button

---

content/community/write-a-blog-post/contents.lr
themes/vocabulary_theme/templates/blog-post.html
themes/vocabulary_theme/templates/cc-search-guide.html
themes/vocabulary_theme/templates/page-with-toc.html
webpack/sass/main.scss

This fixes the content issue. Replaces markdown class with content.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Replace markdown with content

---

webpack/js/main.js

This PR makes 'Table of content" Component on the guidelines page reactive.
Adds a function which removes and adds .is-active class on hashchange.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```

Update navigation function

---

content/community/contents.lr

Updates the table of the overview page in community section. Path - /community/
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Update table on community overview page

---

themes/vocabulary_theme/templates/blog.html
themes/vocabulary_theme/templates/community_team_list.html
themes/vocabulary_theme/templates/page-with-toc.html
themes/vocabulary_theme/templates/search_roadmap.html
webpack/sass/main.scss

This removes multiple instances of `.title` and adds one global instance.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Remove multiple instances of title class

---

themes/vocabulary_theme/templates/layout.html

Adds global header.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Add global header

---

themes/vocabulary_theme/templates/404.html

This updates 404 page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update 404 template.

---

webpack/sass/main.scss

This updates padding of the featured project section on the home page and Project list page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update padding in featured sections

---

webpack/sass/main.scss

This PR adds different padding for mobile and desktop version of single post page. Path - `/blog/entries/data-flow-API-to-DB/`. ALso makes `.content `class global.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the …
```

Fix padding for single post page.

---

content/contributing-code/cc-search/contents.lr
themes/vocabulary_theme/templates/404.html
webpack/sass/main.scss

This fixes spacing problems on CC search guidelines page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Fix spacing issue on CC search guidelines page

---

themes/vocabulary_theme/templates/project-ideas.html
themes/vocabulary_theme/templates/search_roadmap.html
webpack/sass/main.scss

This PR updates spacing in Project Ideas and CC search roadmap page.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Updating spacing on project ideas and CC search pages.

---

content/blog/entries/smithsonian-unit-code-update/contents.lr

GSoC 2020- second blog post
Blog post on updating the unit codes in Smithsonian
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

GSoC blog post 2- Smithsonian unit code update

---

content/community/community-team/contents.lr
content/community/community-team/project-roles/contents.lr

Update the text in the description of community teams and that of particular roles.
The PR handles the merge of Project Members into Project Collaborators. It also updates text that suggests a heirarchy in the community teams to clarify that they are not oriented vertically but rather differ only in the level of involvement one has previously shown and wishes to show in the future.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```

Change copy related to Community Teams

---

content/community/community-team/project-roles/contents.lr

index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Removed duplicate line

---

themes/vocabulary_theme/templates/community_team_list.html

This replaces spacing classes with `.content` class on Community team page.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Update community team page.

---

themes/vocabulary_theme/templates/blocks/hero.html
webpack/sass/main.scss

Fixes #383 #384 by @panchovm
This PR updates the hero section and fixes the column and placement problems.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update image and columns for the hero section.

---

webpack/sass/main.scss

Fixes #386 #387 #389  by @panchovm
This PR updates get-involved section on home page. It changes -
1. Text color of paragraphs.
2. Hover color of links.
3. Add separation border to this section.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole …
```

Update get involved section.

---

themes/vocabulary_theme/templates/blocks/featured-projects.html
themes/vocabulary_theme/templates/blocks/recent-posts.html

Fixes #390 by @panchovm
This updates Recent posts and Featured project titile to 2A.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```

update titles for two sections

---

webpack/sass/main.scss

Fixes #392 ,#393, #395 by @panchovm
This updates -
1. Vertical spacing of breadcrumb
2. Text color of single post body content
3. Code text style- Changes border color
index.md`).
<details>
```
Version 1.1
Suite D4700
have …
```

Update single post page.

---

themes/vocabulary_theme/templates/authors.html
themes/vocabulary_theme/templates/macros/authors.html
webpack/sass/main.scss

Fixes #405 by @panchovm
This fixes all the problems stated in the issue.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

update authors page

---

themes/vocabulary_theme/templates/layout.html

Fixes #382 by @Dhruvi16 
This updates logo size as per mockups.
Update size in viewbox
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update logo size

---

content/contents.lr
templates/layout.html

Fixes #412  by @TrustedMercury
Fixes the following HTML errors - 
- Removes the `name` attribute from the `<nav>` element as it's deprecated in HTML5
- Removed the `align` attribute from the `<div>` elements as it's deprecated in HTML5
- Fixed unclosed `<div>` element inside `<nav>`
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```

Resolved mentioned HTML errors in #412

---

templates/layout.html

Moves GitHub corner outside the bounds of the navbar, directly under the `<body>` element to ensure it always positions itself in the corner of the document.
The component was misaligned because it is `absolute`-positioned, causing it to stick to the first `relative`-positioned element, which happened to be the navbar.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Move GitHub link outside the bounds of the navbar

---

webpack/sass/main.scss

Fixes #394 by @panchovm
This changes the text color of description to `dark-slate-gray`.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update text color

---

content/contributing-code/cc-search/contents.lr
themes/vocabulary_theme/templates/cc-search-guide.html
webpack/sass/main.scss

Fixes #399 by @panchovm
This fixes the text style and the navigation of the CC search guidelines page.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated …
```

Update text styles and navigation for CC Search guidelines page.

---

themes/vocabulary_theme/templates/blocks/featured-projects.html
themes/vocabulary_theme/templates/project_list.html

This PR makes all the links to the project slack channels working.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

update slack links

---

themes/vocabulary_theme/templates/cc-search-guide.html
webpack/js/main.js

Fixes #400 by @panchovm
Fixes part 2 and 3 of the issue.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Fix table of progress.

---

themes/vocabulary_theme/templates/project-ideas.html
webpack/sass/main.scss

Fixes #403 #402 #401 by @panchovm
This fixes all the problems on project ideas page.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```

Fix problems on project ideas page

---

themes/vocabulary_theme/templates/page-with-toc.html

Adds Usability to Sidebar menu. 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

add usability to contibution guidelines sidebar

---

webpack/sass/main.scss

Fixes #404 by @panchovm
This removes the border from the last row cards.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

remove divider from last row of blog page.

---

content/blog/entries/blank_profile.svg
themes/vocabulary_theme/templates/macros/posts.html

Fixes #446 by @kgodey 
This updates archive blogs spacing and fix missing avatars.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```

update profile images condition

---

webpack/sass/main.scss

Fixes #442 by @kgodey 
Replaces the class name to apply the style.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Fix project ideas spacing issue.

---

themes/vocabulary_theme/templates/blocks/featured-projects.html
themes/vocabulary_theme/templates/project_list.html

Fixes #437 by @kgodey 
This adds a condition to slack links.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

add condition to slack link

---

webpack/sass/main.scss

Fixes #439 by @kgodey 
This fixes styles of pre element.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

fix style for multiple lines of code

---

content/contents.lr
themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/project_list.html

Fixes #443 by @kgodey 
Adds external link icons and changes link color.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

fix link styling for the repo on Project list page.

---

content/blog/entries/2020-03-05-involucrate-gsoc-outreachy-es/contents.lr
content/blog/entries/2020-03-05-participe-gsoc/contents.lr
content/blog/entries/cc-platform-toolkit-revamp-2/contents.lr
content/blog/entries/cc-platform-toolkit-revamp-3/contents.lr
content/blog/entries/cc-platform-toolkit-revamp-4/contents.lr
content/blog/entries/cc-platform-toolkit-revamp/contents.lr
content/blog/entries/cc-vocabulary-my-first-four-weeks/contents.lr
content/blog/entries/cc-vocabulary-week5-8/contents.lr
content/blog/entries/cc-vocabulary-week9-13/contents.lr
content/blog/entries/improving-cc-license-chooser-coding/contents.lr
content/blog/entries/improving-cc-license-chooser-outcomes/contents.lr
content/blog/entries/improving-cc-license-chooser-weeks-1-2-design/contents.lr
content/blog/entries/integration-vocabulary-ccos/contents.lr
content/blog/entries/legal-database-a-new-beginning/contents.lr
content/blog/entries/legal-database-coding-mid-term/contents.lr
content/blog/entries/legal-database-design/contents.lr
content/blog/entries/legal-database-features/contents.lr
content/blog/entries/resource-gathering/contents.lr
content/blog/entries/takeaways-from-my-FOSS-journey/contents.lr
content/blog/entries/what-is-up-ccos/contents.lr
content/blog/entries/why-lektor/contents.lr

Outreachy did not have year specific tags, so #459 added them. This PR attaches those tags to blogs written by the Outreachy interns.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```

Update tags on blogs written by Outreachy interns

---

themes/vocabulary_theme/templates/layout.html

index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Remove plural of Teams from footer.

---

content/blog/authors/annatuma/contents.lr
content/blog/categories/collaboration/contents.lr
content/blog/entries/2020-08-x5gon-cc-catalog-api/contents.lr

index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Added Anna's blog post announcing X5GON collaboration

---

content/blog/authors/mathemancer/contents.lr

index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Correct MD5 hash

---

themes/vocabulary_theme/templates/blog-post.html

This updates the current blog post title in the series.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Update current blog link in the series.

---

content/contents.lr

Updates twitter links and directs it to CC open source and not CC.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

update twitter links

---

content/blog/entries/cc-search-accessibility-week9-10/contents.lr
content/blog/entries/cc-search-accessibility-wrapup/contents.lr

Fixes #[issue number] by @[issue author]
Adds Ayan's final blog.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

add ayan final blog

---

content/contributing-code/contents.lr
content/contributing-code/github-repo-guidelines/contents.lr
content/contributing-code/repo-labels/contents.lr
themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/page-with-toc.html
webpack/sass/main.scss

This PR
- updates the guide about finding available issues based on the new labels
- adds an entire page about the new labels
- updates references to point to this page rather than the JSON file in the repo
This PR also modifies the Sass file `main.scss` adding what is essentially a new "component" that does not have a correspondent in Vocabulary.
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it …
```

New code contrib guide

---

content/community/contents.lr
content/internships/applicant-guide/contents.lr
themes/vocabulary_theme/templates/project-ideas.html

Replaces all occurrences of `cc-gsoc-outreachy` with `cc-dev-internships` to match the corresponding change of name on Slack.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```

Rename the internships channel on Slack

---

content/archives/contents.lr
themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/page-with-title.html

Fixes #498 by @zackkrida
Moves header archive items to the `/archives` page (using a new `page-with-title.html` template), and adds an "Archives" link to the footer.
index.md`).
<details>
```
Version 1.1
Suite D4700
have …
```

Fix archives page, Remove archives from header, Add archives to footer

---

content/community/contents.lr

This adds three slack channels to the community page:
- # cc-dev-icmi
- # cc-dev-ipa , and
- # cc-dev-lcga .
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

add new slack channels to community page

---

content/blog/authors/ariessa/contents.lr
content/blog/categories/cc-catalog-api/contents.lr
content/blog/entries/add-query-using-curl-command-and-provide-response-samples/contents.lr
content/blog/series/gsod-2020-cccatalog-api-usage-guide/contents.lr

Added new blog entry, series, author, and category.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Added new blog entry

---

.flake8
Pipfile
Pipfile.lock
packages/checkfile/lektor_checkfile.py
packages/checkfile/setup.py
packages/markdown-table/setup.py
pyproject.toml
webpack/package-lock.json
webpack/package.json

- Remove minor version from Pipfile python to allow latest Python 3 version (3.8)
- Added black, black configuration, and reformatted python files using black
- Added flake8, flake8 configuration, and updated python files per flake8
- Update webpack (fixed 2 security issues)
- [Black](https://github.com/psf/black), *the uncompromising Python code formatter*
- [flake8](https://gitlab.com/pycqa/flake8), *a python tool that glues together pep8, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code.*
Performed local spot checks with `pipenv run lektor server -f webpack` running.
index.md`).
<details> …

Python and Webpack Dev Updates

---

webpack/js/components.js

It fixes the link in the issue finder page.
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified …

Fix issue link in the Issue finder page

---

webpack/js/components.js

Fixes #517  by @dhruvkb 
Used ISO-8601 date format on the issue finder as mentioned in issue
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

switched to ISO date format on issue finder

---

content/contributing-code/contents.lr

Fixes #507  by @zackkrida 
Used colored label components in /contributing-code page as mentioned in the issue
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Used colored label component in /contributing-code page

---

content/blog/authors/nimishbongale/contents.lr
content/blog/entries/cc-vocabulary-docs-intro/contents.lr
content/blog/series/gsod-2020-vocabulary-usage-guide/contents.lr

Adds @nimishbongale's blog post to the open source site, which talks about vocabulary and the other relevant details.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```

Add @nimishbongale's first blog post

---

.lektorproject

Fixes #516  by @dhruvkb 
This pr changes [.lektorproject](https://github.com/creativecommons/creativecommons.github.io-source/blob/6ff9518c0526f494a77a0ca6ebb3d8e307dc9639/.lektorproject#L5) so that .cc-metadata.yml file is generated upon building 
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I …
```

Generate .cc-metadata.yml file

---

content/blog/entries/cc-wp-plugin-attribution-for-images/contents.lr

<details>
```
Version 1.1
Suite D4700
work with …
```

Added link to NoWorries project

---

webpack/js/components.js
webpack/sass/issue-finder-page.scss

Fixes #[issue number] by @[issue author]
Added disclaimer on the skill filter in the issue finder
Made changes and tested locally.
index.md`).
<details>
```
Version 1.1
Suite D4700
By contributing to this project, I certify that:
(a) The contribution was created in whole or in part by me and me
have the right to submit it under the open-source license …
```

Added disclaimer on the skill filter in the issue finder

---

content/contributing-code/python-guidelines/contents.lr
themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/page-with-toc.html

Fixes #276
add Python Guidelines
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

add Python Guidelines

---

content/blog/entries/cc-vocabulary-docs-updates-1/contents.lr

Updates @nimishbongale's second blog entry on the CC Technical blog.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Nimish GSoD Blog Post (Vocabulary Site Updates v1)

---

themes/vocabulary_theme/templates/page-with-toc.html
webpack/sass/guidelines.scss

Fixes #490 by @subhamX 
website is responsive now as shown in the screenshot
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

feat: Responsiveness bug

---

webpack/js/components.js
webpack/package-lock.json
webpack/package.json

This PR updates the issue finder to work with the YAML files w.r.t. creativecommons/ccos-scripts#104.
A secondary dependency `js-yaml` had to upped to a direct dependency to parse the YAML files. The build size should consequently stay the same and performance is still very snappy.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```

Update issue finder to work with the YAML files

---

webpack/js/components.js

Add the functionality to find issues with the label `🏷 status: label work required`.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```

Create a new aim filter

---

themes/vocabulary_theme/templates/layout.html

Adds the appropriate tracking query parameters to the footer donation url, updating the link to `https://creativecommons.org/donate?c_src=website&c_src2=GlobalFooter`
index.md`).
<details>
```
Version 1.1
Suite D4700
have …
```

Add tracking query parameters to footer donation link

---

content/blog/entries/cc-vocabulary-docs-updates-closing/contents.lr

- Adds a "My Learnings & Challenges" section meeting the [GSoD work product](https://developers.google.com/season-of-docs/docs/work-product#good_examples_of_how_to_describe_your_work
) requirements to my final report post
- Fixes some punctuation errors
Just tagging you here @dhruvkb 😄 
index.md`).
<details>
```
Version 1.1
Suite D4700
By …
```

Update final report to adhere to GSoD work report guidelines

---

content/blog/entries/2020-12-07-upcoming-changes-to-community/contents.lr

<details>
```
Version 1.1
Suite D4700
work with …
```

Added blog post announcing community team changes.

---

content/contributing-code/repo-labels/contents.lr

Add the `🙅 status: discontinued` label.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```

Add discontinued label to the list

---

content/community/contents.lr

- Remove Slack channels for maintenance projects (per [Upcoming Changes to the CC Open Source Community — Creative Commons Open Source](https://opensource.creativecommons.org/blog/entries/2020-12-07-upcoming-changes-to-community/))
- Replace HTML table with Markdown table
- Re-flow text and use reference style markdown links
- (related to https://github.com/creativecommons/tech-support/issues/724 [private repo])
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```

remove maintenance channels and reformat

---

content/community/code-of-conduct/contents.lr
content/community/code-of-conduct/enforcement/contents.lr

Fixes #583 by @kgodey 
- Code of Conduct Enforcement
- Update CoC Committee
- Update format/style
- Update section organization
- move current committe to be a subheading of The Code of Conduct Committee
- make Last Revised a subheading of Policy Revision and link to comits
- Code of Conduct
- Link to  Code of Conduct Enforcement in content
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```

CoC Committee update and format/style changes

---

themes/vocabulary_theme/templates/page-with-toc.html

Fixes #568  by @dhruvkb 
Simplified 'Page with ToC' template using the features of Jinja templates.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in …
```

Code cleanup in 'Page with ToC' template

---

content/internships/applicant-guide/contents.lr
content/internships/contents.lr
models/project-idea.ini
themes/vocabulary_theme/templates/project-ideas.html

minor updates to intern overview, appl guide, and project formatting
- overview
- updated mentors
- application guide
- added internal links
- updated formatting & whitespace
- project ideas formatting
- skills and mentors fields are now markdown so they can be lists
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```

minor updates to intern overview, appl guide, and project formatting

---

content/blog/authors/TimidRobot/contents.lr

updated my bio
index.md`).
<details>
```
Version 1.1
Suite D4700
of my …
```

updated my bio

---

content/blog/authors/zackkrida/contents.lr

updated my bio
index.md`).
<details>
```
Version 1.1
Suite D4700
of my …
```

Update zackkrida bio

---

content/internships/project-ideas-collection/add-cc-chooser-wordpress/contents.lr
content/internships/project-ideas-collection/licenses-machine-readable/contents.lr
content/internships/project-ideas-collection/vocabulary-performance/contents.lr
content/internships/project-ideas-collection/vocabulary-remove-bulma/contents.lr
content/internships/project-ideas-collection/wordpress-remove-queulat/contents.lr
themes/vocabulary_theme/templates/project-ideas.html
webpack/js/ideas.js

add GSoC 2021 project ideas
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
```

add GSoC 2021 project ideas

---

content/internships/contents.lr

fix slack handle
index.md`).
<details>
```
Version 1.1
Suite D4700
of …
```

fix slack handle

---

content/internships/applicant-guide/contents.lr

fix application template link
(i introduced error in #593)
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

fix application template link

---

content/internships/project-ideas-collection/licenses-machine-readable/contents.lr

fix mentor pool for Licenses Machine Readable Information
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

fix mentor pool

---

content/contributing-code/python-guidelines/contents.lr

italicize quotes
index.md`).
<details>
```
Version 1.1
Suite D4700
of …
```

italicize quotes

---

content/internships/applicant-guide/contents.lr
content/internships/contents.lr
content/internships/history/contents.lr

remove GSoC 2021 organization application specifics and fix broken links
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

no GSoC 2021 and fix broken links

---

.github/workflows/lektor-build-deploy.yml
Pipfile
Pipfile.lock
README.md
packages/checkfile/lektor_checkfile.py
packages/checkfile/setup.py
packages/markdown-table/lektor_markdown_table.py
packages/markdown-table/setup.py
pyproject.toml

- update install docs
- update python version and dependencies/tooling
- update style/syntax per black & isort
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Python updates

---

content/contributing-code/javascript-guidelines/contents.lr
themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/page-with-toc.html

Fixes #509 by @zackkrida 
Add JavaScript code guidelines, including:
- formatting
- tooling
- philosophy/values (for guidance when there isn't a simple answer)
Adding a new page and ToC links.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or …
```

Add JavaScript guidelines

---

content/contributing-code/javascript-guidelines/contents.lr

Fixes #618  by @brylie
Adds a brief description of the importance of simplicity in the context of web engineering. Also adds a river metaphor related to stability/maturity.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Add section on Simplicity and river-delta metaphor 

---

content/blog/entries/2022-01-06-cc-messaging/contents.lr

add CC Messaging Update 2022Q1 (Dropping IRC) post
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```

add CC Messaging Update 2022Q1 (Dropping IRC) post

---

content/internships/project-ideas-collection/chooser-stewardship/contents.lr

Fixes #630 by @brylie
Closes https://github.com/creativecommons/chooser/issues/383
Adds an internship idea for "Chooser project stewardship", in preparation for the GSoC application process. 
The Google Summer of Code [suggests making an idea page](https://google.github.io/gsocguides/mentor/making-your-ideas-page), which we already have. This PR adds a "Chooser stewardship" project to our internship ideas section.
index.md`).
<details>
```
Developer …
```

Add Chooser project stewardship description

---

content/contents.lr

Fixes #629 
- #629
update homepage following CC Search transfer:
- replace CC Catalog API with Chooser
- remove CC Search Browser Extension
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

update homepage following CC Search transfer

---

.lektorproject
Pipfile
Pipfile.lock

update Python packages
Last two Python update:
- #620
- #613 
- Ensured `pipenv run lektor server -f webpack` run locally without errors (there are some warnings)
- Verified `/contributing-code/issue-finder/` page works as expected
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy …
```

update Python packages

---

webpack/package-lock.json
webpack/package.json

update npm packages (and resolve security warning)
Ran `npm update` twice, update updated `node-sass` to version 7, then ran it twice more:
```
added 15 packages, removed 15 packages, changed 118 packages, and audited 515 packages in 11s
```
```
changed 1 package, and audited 515 packages in 3s
```
```
added 56 packages, removed 22 packages, changed 25 packages, and audited 549 packages in 3s
```
```
up to date, audited 549 packages in 3s
50 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
Last two npm update:
- #620
- Ensured `pipenv run lektor server -f webpack` run locally without errors (there are some warnings)
- Verified `/contributing-code/issue-finder/` page works as expected
index.md`). …

update npm packages

---

.github/workflows/lektor-build-deploy.yml
CODE_OF_CONDUCT.md
README.md
assets/CODE_OF_CONDUCT.md
content/blog/entries/cc-vocabulary-docs-updates-closing/contents.lr
content/blog/entries/saltstack-host-classification/contents.lr
content/community/code-of-conduct/enforcement/contents.lr
content/community/write-a-blog-post/contents.lr
content/contributing-code/github-repo-guidelines/contents.lr
databags/repos.json
webpack/js/components.js

Fixes #617 
- #617
update/correct default branch names
- (including references to other repositories with an updated default branch name)
- [[Meta] Support "main" as a default branch name · Issue #1125 · creativecommons/creativecommons.org](https://github.com/creativecommons/creativecommons.org/issues/1125)
index.md`).
<details>
```
Version 1.1
1 …
```

update/correct default branch names (master => main)

---

content/community/community-team/engagement-channels/contents.lr
content/community/community-team/project-roles/contents.lr
content/community/contents.lr
content/gsoc-2019/application-instructions/contents.lr
content/gsoc-2019/project-ideas/contents.lr
content/gsoc-2019/student-expectations/contents.lr
content/programs/applicant-guide/contents.lr
content/programs/contrib-guide/contents.lr
content/programs/lead-guide/contents.lr
content/programs/project-ideas-collection/add-cc-chooser-wordpress/contents.lr
content/programs/project-ideas-collection/chooser-stewardship/contents.lr
content/programs/project-ideas-collection/legal-tools-machine-layer/contents.lr
themes/vocabulary_theme/templates/project-ideas.html

Fixes #641 
- #641 
- Completes Work Programs reorganization
- Correct links and redirects
- Miscellaneous clean-ups (ex. remove IRC documentation)
- Part 1: #642
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```

Work Programs reorganization Part 2

---

content/blog/categories/outreachy-2021/contents.lr
content/blog/entries/building-the-cc-global-components-library/contents.lr
content/programs/history/contents.lr

add/update outreachy 2021 links & navigation
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

add/update outreachy 2021 links & navigation

---

.lektorproject
Pipfile.lock
webpack/package-lock.json

Python and webpack/node/npm updates
- ensure `pipenv run lektor server -f webpack` runs locally without errors (there are some warnings)
npm update output:
```
added 4 packages, removed 6 packages, changed 48 packages, and audited 547 packages in 12s
50 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
I verified that `http://127.0.0.1:5000/contributing-code/issue-finder/` works as expected. It is the page most likely to break due to npm upates.
index.md`). …

Update dependencies (Python & NPM)

---

themes/vocabulary_theme/templates/author.html

Fixes #646
- #646 
add content class (required due to Bulma invasive reset)
- [Content | Bulma: Free, open source, and modern CSS framework based on Flexbox](https://bulma.io/documentation/elements/content/)
- [Is it possible to "remove" minireset css? · Issue #2553 · jgthms/bulma](https://github.com/jgthms/bulma/issues/2553)
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```

add content class (required due to Bulma invasive reset)

---

content/community/code-of-conduct/contents.lr
content/community/code-of-conduct/enforcement/contents.lr

Fixes #503
- #503 
- Update Code of Conduct
- Update for Contributor Covenant v2.1
- Old: [`7ab85dfc09/content/community/code-of-conduct/contents.lr`](https://github.com/creativecommons/creativecommons.github.io-source/blob/7ab85dfc09d69a18e579c6985184c6e8e827b8e0/content/community/code-of-conduct/contents.lr)
- New: [`930cf77317/content/community/code-of-conduct/contents.lr`](https://github.com/creativecommons/creativecommons.github.io-source/blob/930cf77317f274e380f283bd0e3cd9698ff2a45c/content/community/code-of-conduct/contents.lr)
- Update Code of Conduct Enforcement
- Update for Contributor Covenant v2.1
- Update committee members
- Fix history link
- Add Terms of Use
- Clean-up whitespace
- Old: [`7ab85dfc09/content/community/code-of-conduct/enforcement/contents.lr`](https://github.c …

update for Contributor Covenant v2.1

---

README.md
content/contributing-code/github-repo-guidelines/contents.lr
webpack/js/components.js

- Fix URLs following https://github.com/creativecommons/ccos-scripts/pull/143
- Document external data
- Update *default branch* name to `main`
- Little bit of formatting tidying
index.md`).
<details>
```
Version 1.1
Suite D4700
license …
```

Fix URLs following ccos-script reorganization

---

content/contributing-code/contents.lr

Fixes #79
- #79 
Add donations section and tidy formatting
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I …
```

add donations section and tidy formatting

---

content/blog/authors/sara/contents.lr
content/programs/applicant-guide/contents.lr
content/programs/contents.lr
content/programs/lead-guide/contents.lr
content/programs/project-ideas-collection/add-plain-text-format-to-cc-legal-tools/contents.lr
content/programs/project-ideas-collection/add-rdf-xml-format-to-cc-legal-tools/contents.lr
content/programs/project-ideas-collection/modernize-termination-of-transfer-wp-plugin/contents.lr
content/programs/project-ideas-collection/refactor-cc-meta-search/contents.lr
themes/vocabulary_theme/templates/project-ideas.html
webpack/js/ideas.js

- Add project ideas for Outreachy 2022 December
- Update project idea filters to match current ideas
- Add Sara as project lead and author
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Outreachy 2022 Dec project ideas

---

content/programs/contents.lr

update programs overview page for Outreachy December 2022 to March 2023 Internships
just a couple of changes i forgot to include in #664 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

update programs overview page for Outreachy December 2022

---

content/contributing-code/python-guidelines/contents.lr

python guidelines: reorganize, fix links, and update formatting
Thank you @possumbilities for contributing feedback that informed these changes
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```

python guidelines: reorganize, fix links, and update formatting

---

content/blog/entries/2022-11-11-calver-to-semver/contents.lr

Fixes https://github.com/creativecommons/tech-support/issues/833 (private repo)
Add **CalVer to SemVer** blog post
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```

add blog post CalVer to SemVer

---

content/community/contents.lr

Addresses: 
* #680
edits `/content/community/contents.lr` file to list the new slack channel `#cc-dev-searchportal`
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```

Add `#cc-dev-searchportal` slack channel listing to `community slack page`

---

models/blog-post.ini
themes/vocabulary_theme/templates/blocks/recent-posts.html
themes/vocabulary_theme/templates/blog-post.html
themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/macros/author_posts.html
themes/vocabulary_theme/templates/macros/authors_byline.html
themes/vocabulary_theme/templates/macros/authors_gravatar.html
themes/vocabulary_theme/templates/macros/posts.html

Improve author support:
- support multiple blog post authors
- it's not obvious in screenshots, but the gravatar image is only for first author listed
- support blog posts with missing author entries
- reduce code duplication
- BONUS!: fix blog link to skip redirect
(I temporarily added some fake names to the most recent blog post to illustrate behavior)
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 …
```

Improve blog author support

---

content/programs/applicant-guide/contents.lr

Update and clarify work program information
- [Contractions  |  Google developer documentation style guide  |  Google Developers](https://developers.google.com/style/contractions)
Related to https://github.com/creativecommons/tech-support/issues/974 (private repo)
index.md`).
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```

Work Program prep

---

content/blog/authors/annatuma/contents.lr

update Anna's job title
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```

update Anna's job title

---

content/programs/contents.lr

document participation in gsoc 2023
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

document participation in gsoc 2023

---

themes/vocabulary_theme/templates/author.html

Fixes #699 by @justaskulkarni.
- #699
Used Bulma to make the authors page responsive.
I figured out that the responsiveness issue was only for tablet screens.
Earlier code:
Updated code:
is-one-fifth doesn't give the desirable responsiveness, therefore, I went for is-one-quarter.
Responsiveness is achieved as demonstrated below:
https://user-images.githubusercontent.com/98650743/222244074-4779b86e-8e21-4a55-a14b-35ae94bd19fd.mp4
index.md`).
<details> …

Made authors page responsive

---

content/contributing-code/contents.lr
content/programs/applicant-guide/contents.lr

Fixes #700 
corrected the punctuation and grammatical errors on :
https://opensource.creativecommons.org/programs/applicant-guide/#contributing
https://opensource.creativecommons.org/contributing-code/
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```

corrected some minute docs mistakes.

---

content/blog/entries/2023-03-24-community-contributions/contents.lr

- add blog post: Thinking More Openly About Working In The Open
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this …
```

add blog post: Considering Community Contributions at Creative Commons

---

content/blog/authors/shafiya/contents.lr
content/blog/entries/2023-06-16-new-chapter-of-my-professional-life/contents.lr

Added authors directory named `shafiya` and created entries directory named `2023-06-16-new-chapter-of-my-professional-life` to create my blog post
Tested locally and it is working as expected.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```

My first blog post

---

content/community/supporters/contents.lr
themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/page-with-toc.html

add Supporters page
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```

add Supporters page

---

content/blog/entries/2023-08-25-machine-layer/contents.lr

fix cc-legal-tools-app link
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

fix cc-legal-tools-app link

---

webpack/package-lock.json

upgrades node modules in `webpack/package-lock.json`
`````
added 3 packages, removed 1 package, changed 40 packages, and audited 236 packages in 11s
found 0 vulnerabilities
`````
`localhost:5000/contributing-code/issue-finder/`
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```

update node modules

---

webpack/sass/main.scss

Fixes #725 by @possumbilities @RohanJacob23
This pull request is for the navbar issue that arises on the mobile view where the logo takes the space of the hamburger icon which pushes it outside the mobile view.
Changed the main.scss file giving 100% width to the svg. (credits: @RohanJacob23)
Before:
After:
index.md`).
<details>
```
Version 1.1
1 …
```

responsive navbar logo fix

---

README.md

- #752 
replaced the old link with the new one from the pipenv website
Changed to this link:
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```

issue-752/ Fixed the incorrect link

---

content/contributing-code/contents.lr

clarify multiple/overlapping contributions
<details>
<summary>🖼️ Contribution Guidelines — Creative Commons Open Source</summary>
</details>
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

clarify multiple/overlapping contributions

---

content/programs/project-ideas-collection/ansible-dev-env/contents.lr

- update the ansible-dev repo url in ansible-dev-env project 
- Tested locally
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```

update ansible-dev repo url

---

webpack/sass/main.scss

Fixes #711 by @soustab10
- The newsletter form should occupy the full width available to the container. This fixes the issue on mobile screens where the form would not expand to the full available width.
1. Open the web page.
2. Scroll down to the footer and check out the "Subscribe to newsletter" form.
index.md`).
<details>
```
Version 1.1
1 Letterman …
```

Optimize email textbox for mobile view

---

content/programs/project-ideas-collection/ansible-dev-env/contents.lr
content/programs/project-ideas-collection/automating-quantifying-the-commons/contents.lr
content/programs/project-ideas-collection/media-attribution-wp-plugin/contents.lr
content/programs/project-ideas-collection/modernize-cc-resource-archive/contents.lr

clarify GSoC large project duration
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

clarify GSoC large project duration

---

content/community/contents.lr
content/contributing-code/translation-guide/contents.lr

update translation information
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

update translation information

---

.github/workflows/lektor-build-deploy.yml
Pipfile
Pipfile.lock
README.md

- Fixes #775 
- 🟠 [Lektor does not sanitize database path traversal · CVE-2024-28335 · GitHub Advisory Database](https://github.com/advisories/GHSA-wv28-7fpw-fj49)
- Fixes #770 
- 🟡 [Black vulnerable to Regular Expression Denial of Service (ReDoS) · CVE-2024-21503 · GitHub Advisory Database
](https://github.com/advisories/GHSA-fj7x-q9j7-g6q6)
- Update Python to 3.11
- Update Python modules
- Update workflow for current actions and improve organization
- Remove lektor-google-analytics link from README
- #721 
```diff
--- piplist.old	2024-04-08 08:44:07
+++ piplist.new	2024-04-08 08:44:07
@@ -3 +3 @@
-black              24.1.1
+black              24.3.0
@@ -5 +5 @@
-certifi            2023.11.17
+certifi            2024.2.2
@@ -13 +12,0 @@
-importlib-metadata 7.0.1
@@ -18,2 +17,2 @@
-Lektor …
```

Update Python, GitHub Actions workflow, and README

---

content/blog/entries/building-the-cc-global-components-library/contents.lr

cc-global-components repo archived: update link to repo
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I …
```

cc-global-components repo archived: update link to repo

---

content/blog/authors/nimishbongale/contents.lr
content/blog/entries/2022-11-11-calver-to-semver/contents.lr
content/blog/entries/cc-platform-toolkit-revamp-4/contents.lr
content/blog/entries/cc-vocabulary-docs-updates-3/contents.lr
content/blog/entries/cc-vocabulary-docs-updates-closing/contents.lr
content/blog/entries/cc-vocabulary-week9-13/contents.lr
content/community/write-a-blog-post/contents.lr
content/contributing-code/github-repo-guidelines/contents.lr

* changes links in multiple posts and pages that reference what is the now archived `cc-archive/vocabulary-legacy`
* [Corrects the link](https://github.com/creativecommons/creativecommons.github.io-source/pull/781/commits/5d21f9816dbe14e11c1990ce028bb2dd64f66830) on [Write A Blog Post](https://opensource.creativecommons.org/community/write-a-blog-post/) page, in the Writing Tips section, that has been going to the wrong file [for a while](https://github.com/creativecommons/creativecommons.github.io-source/blob/b45c51ccc378ba5d7a8dffbc98ecfc6209437a75/content/community/write-a-blog-post/contents.lr).
* Updates [links](https://github.com/creativecommons/creativecommons.github.io-source/pull/781/commits/40c2d93a8a3a147e45342eac36c1c34b6e36051f) to `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` …

update links to `vocabulary-legacy`, fix other errors encountered along the way

---

Pipfile.lock

- Fixes #783 
- 🟡 [Requests `Session` object does not verify requests after making first request with verify=False · CVE-2024-35195 · GitHub Advisory Database](https://github.com/advisories/GHSA-9wx4-h78v-vm56)
- Fixes #786 
- 🟡 [urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects · CVE-2024-37891 · GitHub Advisory Database](https://github.com/advisories/GHSA-34jh-p97f-mpxf)
Update Python modules
```diff
--- piplist.old	2024-06-20 07:20:05
+++ piplist.new	2024-06-20 07:20:05
@@ -2,4 +2,4 @@
-Babel              2.14.0
-black              24.3.0
-blinker            1.7.0
-certifi            2024.2.2
+Babel              2.15.0
+black              24.4.2
+blinker            1.8.2
+certifi            2024.6.2
@@ -10 +10 @@
-flake8             7.0.0
+flake8 …
```

Update Python modules

---

content/contributing-code/repo-labels/contents.lr

- add 📖 aspect: docs
- remove 🎃 Hacktoberfest
- order entries
<details>
<summary>Repository Labels — Creative Commons Open Source</summary>
</details>
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```

add 📖 aspect: docs, remove 🎃 Hacktoberfest, and order entries

---

README.md

corrects `upate` to `update` in README.md
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) …
```

fix typo `upate` to `update`

---

content/blog/authors/NaishaSinha/contents.lr
content/blog/entries/2024-07-10-automating-quantifying/contents.lr

- Fixes profile username (NaishaSinha) from lowercase to mixed case, which resolves the issue of Linux being case sensitive, whereas MacOS is case insensitive.
In the blog `authors` section, changed the username to:
`username: NaishaSinha`
In the actual blog post section, I also updated the username accordingly: `author: NaishaSinha`
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation …
```

Fixed Username From Lower Case to Mixed Case for Linux Case Sensitivity

---

content/blog/entries/2024-07-10-automating-quantifying/contents.lr

After Automating Quantifying the Commons: Part 2 was published, I included those links into the referencing sections of Part 1.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Add Part 2 Blog Links to Part 1 of Automating Blog Posts

---

content/contributing-code/foundational-tech/contents.lr
themes/vocabulary_theme/templates/layout.html

**Add "Foundational technologies" page**. The purpose of this page is to:
- improve onboarding for less experienced contributors
- provide a single location that can be linked to from repository READMEs
Remove monetization meta tag from template:
- Originally added in #494 
- per #483 
- (removal confirmed by @annatuma) 
Also thank you @briandominick! This PR includes content from: 
- creativecommons/cc-legal-tools-app/pull/471
<details>
<summary> 🖼️ Foundational technologies — Creative Commons Open Source</summary>
</details>
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open …

Add "Foundational technologies" page

---

content/contributing-code/foundational-tech/contents.lr

add GitHub fork links to Getting started with GitHub and Git section
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this …
```

add GitHub fork links to Getting started with GitHub and Git section

---

content/blog/entries/contents.lr
content/community/code-of-conduct/contents.lr
content/community/code-of-conduct/enforcement/contents.lr
content/community/community-team/project-roles/contents.lr
content/community/contents.lr
content/community/write-a-blog-post/contents.lr
content/contents.lr
content/contributing-code/github-repo-guidelines/contents.lr
content/contributing-code/issue-finder/contents.lr
content/contributing-code/pr-guidelines/contents.lr
content/contributing-code/repo-labels/contents.lr
content/contributing-code/translation-guide/contents.lr
content/contributing-code/usability/contents.lr
content/programs/applicant-guide/contents.lr
content/programs/contrib-guide/contents.lr
content/programs/lead-guide/contents.lr
themes/vocabulary_theme/templates/community_team_list.html
themes/vocabulary_theme/templates/project-ideas.html
themes/vocabulary_theme/templates/project_list.html

Define Creative Commons (CC) acronym at top of page or on first use
There are 28 content pages (excluding blog content). This pull request (PR) updates 67% of them.
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```

Define Creative Commons (CC) acronym at top of page or on first use

---

content/programs/contents.lr

update program participation
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

update program participation

---

themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/macros/authors_gravatar.html

- Partially fixes #815 by @ginabeki
This PR addresses the following accessibility issues:
1. Ensured that all links contain meaningful text where necessary and added aria-labels for improved screen reader accessibility.
2. Cross-checked all image tags to confirm the presence of descriptive alt text, and updated or added alt text where appropriate for better understanding.
3. Verified that all forms adhere to the requirements outlined in the design system, improving accessibility and usability.
4. Added the document language attribute (<html lang="en">) to improve how screen readers interpret the content.
A comprehensive accessibility audit of all  files in the templates was conducted, to systematically identify and resolve issues. Addressing these concerns will improve the user …

[Accessibility]  Corrected  accessibility issues found on website

---

webpack/sass/home-page.scss

- Fixes #836 by @SumaiyaaRq
This PR solves the issue of 'overflowing heading in mobile devices causing scrolling' by adding specific styles  for smaller devices using media queries.
**Modified:** `homepage.scss` file by adding media queries for devices having with <=530px.
1. Open the project.
2. Right-click and select Inspect (or press Ctrl+Shift+I / Cmd+Option+I on Mac).
3. Click Toggle Device Toolbar (or press Ctrl+Shift+M / Cmd+Shift+M on Mac ).
4. Select small screen size
5. See correction.
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain …

BugFix: Fixes Heading Overflow in  mobile devices

---

webpack/package-lock.json

- Fixes #788 
- 🟠 [Uncontrolled resource consumption in braces · CVE-2024-4068 · GitHub Advisory Database](https://github.com/advisories/GHSA-grv7-fg5c-xmjg)
- Fixes #806
- 🟡 [Webpack's AutoPublicPathRuntimeModule has a DOM Clobbering Gadget that leads to XSS · CVE-2024-43788 · GitHub Advisory Database](https://github.com/advisories/GHSA-4vvj-4cpr-p986)
- Update NPM modules
- _added 6 packages, removed 21 packages, changed 78 packages, and audited 222 packages in 7s_
```shell
cd webpack
npm list --package-lock-only --all > npmlist.old
git checkout npm-updates
npm list --package-lock-only --all > npmlist.new
diff -u npmlist.old npmlist.new
```
```diff
--- npmlist.old	2023-08-31 06:29:42
+++ npmlist.new	2024-11-05 06:50:09
@@ -1,77 +1,60 @@
-webpack@ …
```

Update NPM modules

---

themes/vocabulary_theme/templates/project_list.html

- Related to #861 by @Queen-codes 
This PR refactors the current project list code to align with vocabulary markup
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```

refactored project list page

---

themes/vocabulary_theme/templates/project-ideas.html

- Related to  #859  by @Queen-codes 
This PR refactors the header section and the current work-programs cards to match the ongoing initiatives markup in `program-index.html` context in vocabulary. 
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```

refactored project-idea page to align with vocab markup

---

Pipfile.lock

- Fixes #875 
- 🟡 [Jinja has a sandbox breakout through indirect reference to format method · CVE-2024-56326 · GitHub Advisory Database](https://github.com/advisories/GHSA-q2x7-8rv6-6q7h)
- 🟡 [Jinja has a sandbox breakout through malicious filenames · CVE-2024-56201 · GitHub Advisory Database](https://github.com/advisories/GHSA-gmj6-6f8f-6699)
Update Python modules (Jinja2@3.1.5, etc.)
```shell
pipenv run pip list > piplist.old
git checkout -b update-python
pipenv update --dev
pipenv run pip list > piplist.new
gsed -e'/^---/d' -i piplist.*
diff -u piplist.old piplist.new
```
(`gsed` is GNU Sed installed via Homebrew. The binary name may simply be `sed` on your system, if you use GNU/Linux.)
```diff
--- piplist.old	2025-01-08 08:56:03
+++ piplist.new	2025-01-08 08:56:03 …
```

Update Python modules (Jinja2@3.1.5, etc.)

---

models/blog.ini
themes/vocabulary_theme/templates/blog.html
themes/vocabulary_theme/templates/macros/pagination.html

- Related to  #860  by @Queen-codes 
This PR sets the body of `blog.html` to have a class of `blog-index` so to apply styling from vocabulary. It also adds the `body-class` field to the `blog.ini` file
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```

Fix: added blog-index class to blog.html's body

---

themes/vocabulary_theme/templates/404.html

- Related to #877  by @[issue author]
This PR refactors the `404.html` page to align with the vocabulary markup. This markup follows the 404 page for the [Creative Commons website](https://creativecommons.org/vuk)
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```

refactored 404 page to align with vocab markup

---

themes/vocabulary_theme/templates/layout.html
themes/vocabulary_theme/templates/page-with-title.html

- Related to #878  by @Queen-codes 
This PR refactors `page-with-title.html` which serves as the template for the cc-tech-archives page to align with vocabulary markup
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```

refactored cc-tech-archive to align with vocab markup

---

themes/vocabulary_theme/templates/cc-search-guide.html
themes/vocabulary_theme/templates/search_roadmap.html

- Related to #879  by @Queen-codes 
This PR aligns the header component with vocabulary markup and removes legacy class names from the markup.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

[Feat]: refactored cc search page[archived] to align with vocab markup

---

assets/static/css/issue-finder.css
themes/vocabulary_theme/templates/issue_finder.html
webpack/js/issue-finder.js

- Fixes #889  by @Queen-codes 
- added new `issue-finder.css` file to add styles for the issue-finder page.
- restyled based on the current styling on the current style for the page
index.md`).
<details>
```
Version 1.1
Suite D4700
license …
```

feat: restyled CC Open Source  issue-finder  page

---

content/blog/entries/2025-01-15-skipping-gsoc-2025/contents.lr
content/blog/entries/2025-01-16-skipping-gsoc-2025/contents.lr
content/programs/contents.lr

Add blog post and update site to announce we're skipping Google Summer of Code (GSoC) 2025 😢 
index.md`).
<details>
```
Version 1.1
Suite D4700
By making …
```

Skipping Google Summer of Code (GSoC) 2025

---

assets/static/css/style.css
themes/vocabulary_theme/templates/search_roadmap.html

- Fixes #896  by @Queen-codes 
- adds class `datatable display` to the `table` element 
- adds class `content` to the `div` container
- adds class `table-container` to add local styles to the table on this page
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```

feat: restyle cc search archive table

---

assets/static/css/style.css
models/blog-post.ini
themes/vocabulary_theme/templates/blog-post.html

- Fixes #892 by @Queen-codes 
- adds `blog-post` class to `blog-post.html`
- adds body-field class to `blog-post.ini` model file
- adds local styling for images to prevent them from overflowing the container
- overrides vocab's styling for `blockquote` and adds local styles(from legacy styling) 
index.md`).
<details>
```
Version 1.1 …
```

adjusted styling on blog post

---

content/blog/entries/outreachy-midpoint-progess-with-creative-commons/contents.lr

This PR adds a blog post: Outreachy Midpoint Progress With Creative Commons
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```

add midterm blog post

---

webpack/js/issue-finder.js

- Fixes #908  by @Queen-codes 
This PR updates the way issue titles are rendered in the `displayFilteredIssues` function.The issue title is now inserted using `textContent` instead of `innerHTML`  to ensure any special characters (like <, >, &) are rendered on the web.
Before: 
Now: 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

fixed special character display bug on issue-finder

---

webpack/js/issue-finder.js

- Fixes #915  by @Queen-codes 
- this pr fixes the bug introduced  by previous pr to properly assign the skill class to skills labels
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

fixed skill not rendering properly on issue-finder

---

assets/static/css/style.css
themes/vocabulary_theme/templates/cc-search-guide.html

- Fixes #917 by @Queen-codes 
- this pr restyles the `cc-search-guide` template for the archived building a new feature in cc search page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

restyled cc-search guide to align with vocab

---

assets/static/vocabulary/css/vocabulary.css

- Fixes #929  by @Queen-codes 
this pr updates the vocabulary in the project, particularly the `vocabulary.css`  file to keep it up to date with the latest version of vocabulary with the commit hash of e32c3cb
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```

update vocabulary to e32c3cb

---

content/blog/entries/reflecting-on-my-outreachy-journey-with-creative-commons/contents.lr

this pr adds the final blog post for the outreach dec 2024 round
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this …
```

add final blog post

---

content/blog/entries/2025-03-06-AWS-RDS-blog-post/contents.lr

During the migration process, I encountered some challenges due to the lack of clarity in the official AWS documentation regarding the MariaDB migration steps. To help others who might face similar issues in the future, I decided to write this blog post. My goal is to provide a clear and practical guide that can simplify the process and help others avoid the difficulties I experienced.
- tested locally 
index.md`).
<details>
```
Developer Certificate …
```

AWS RDS blog post

---

assets/static/vocabulary/css/vocabulary.css

Update Vocabulary to [a421547](https://github.com/creativecommons/vocabulary/tree/a421547df9731f524f36f11c6f428074cfa6ca77) (2025-05-12)
- [creativecommons/vocabulary](https://github.com/creativecommons/vocabulary): _A cohesive system of design for Creative Commons_
index.md`).
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```

Update Vocabulary to a421547

---

assets/static/css/style.css

- Close style.css media stanza (missing "}")
- Remove trailing whitespace
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```

Close style.css media stanza (missing "}")

---

themes/vocabulary_theme/templates/blog.html
themes/vocabulary_theme/templates/issue_finder.html
themes/vocabulary_theme/templates/page-with-title.html
themes/vocabulary_theme/templates/page-with-toc.html

- remove extra `<p></p>` tags (description is parsed markdown content and already has `<p></p>` tags
- clean-up whitespace.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```

remove extra <p></p> tags

---

Pipfile.lock

- Fixes #955 
- 🟡 [urllib3 does not control redirects in browsers and Node.js · CVE-2025-50182 · GitHub Advisory Database](https://github.com/advisories/GHSA-48p4-8xcf-vxj5)
- 🟡 [urllib3 redirects are not disabled when retries are disabled on PoolManager instantiation · CVE-2025-50181 · GitHub Advisory Database](https://github.com/advisories/GHSA-pq67-6m6q-mj2v)
Update Python modules (urllib 2.5.0, etc.)
```shell
pipenv run pip list > piplist.old
git checkout -b update-python
pipenv update --dev
pipenv run pip list > piplist.new
gsed -e'/^---/d' -i piplist.*
diff -u piplist.old piplist.new
```
(`gsed` is GNU Sed installed via Homebrew. The binary name may simply be `sed` on your system, if you use GNU/Linux.)
```diff
--- piplist.old	2025-05-13 15:10:04
+++ piplist.new …
```

Update Python modules (urllib 2.5.0, etc.)

---

content/blog/entries/2025-07-11-refactoring-the-cc-chooser-pt-1/contents.lr
content/blog/entries/2025-10-06-refactoring-the-cc-chooser-pt-2/contents.lr

* adds part 1  blog post for `Refactoring and Releasing the new CC Chooser`
**Note: screenshot is too tall, please view locally!**
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```

add chooser refactor part 1 blog post

---

content/contributing-code/translation-guide/contents.lr

Improve/fix formatting of Translation Guide
| Old/current | New/pull request |
| --- | --- |
| ![Screenshot 2025-10-08 at 07-18-58 Translation Guide — Creative Commons Open Source](https://github.com/user-attachments/assets/b757b2ea-b9f7-42c8-a1ac-9272a44900b6) | ![Screenshot 2025-10-08 at 07-19-13 Translation Guide — Creative Commons Open Source](https://github.com/user-attachments/assets/f28a32ca-dbd1-43f3-af52-5fb71646cd4a) |
index.md`).
<details> …

Improve/fix formatting of Translation Guide
