creativecommons/ccos-website-source

- content/gsoc-2019/project-ideas-collection/reward-and-delight/contents.lr
Due to incorrect markdown formatting (extra parentheses), the hyperlink to the "insights from our research" URL is leading to a dead link--see: http://creativecommons.github.io/gsoc-2019/project-ideas/all/#reward-and-delight
I've removed the extra parentheses
> Fixed formatting issue causing a dead link

- assets/static/style.css
Closes #25 
The design of  https://creativecommons.org website navbar blended perfectly with this. 
Thanks @kgodey for suggesting it.
(screenshots below)
If this fix can be improved, tell me. I would love to improve it.
> [Fix] improve styling for active nav links when navbar has collapsed.#25

- templates/page-with-toc.html
This template fix links each sub-item to the appropriate anchor. See the TOC box on http://creativecommons.github.io/contributing-code/, and you'll notice all the sub-item anchor links are currently not right.
Before this update:
After:
Closes #XX
**Checklist**  
Version 1.1
Suite D4700
(b) …
> Fixed anchors for sub-items in TOC

- content/tech-blog-archives/contents.lr
- content/tech-blog-archives/getting-started-with-hacking-on-the-list/contents.lr
- models/blog-post.ini
- models/blog.ini
- templates/blog-post.html
- templates/blog.html
Adds a blog to Lektor containing old CC technical blog posts.
Old posts are currently located here and not deployed anywhere AFAIK: https://github.com/creativecommons/labs/tree/gh-pages/_posts
**Remaining work**
**Future work**
This work will be done in future pull requests.
- Create author pages that show all of one author's posts.
- Create category pages that show posts associated with a category.
**Checklist**
Version 1.1
Suite D4700
By making a contribution to this project, …
> Publish technical blog archives

- .lektorproject
- configs/atom.ini
- models/blog-post.ini
- templates/blog-post.html
Fixes #75 
- add [lektor-atom](https://www.getlektor.com/plugins/lektor-atom/) plugin. Using it, we can easily create multiple feeds.
- add `[blog]` feed for CC technical blog `content/blog`.
- Add absolute url in project config to remove `E feed.xml (RuntimeError: To use absolute URLs you need to configure the URL in the project config.)` error.
- The feed for blog will be at `creativecommons.github.io/feed.xml`. 
- I also added the `check_file()` function in `blog-post.html` to ensure that we have created an author before publishing a blog post.
- The `select` type of author field in `blog-post.ini` was querying the now absent `/authors`. Changed the type to `string`. 
**Checklist:**
index.md`). …
> integrate lektor-atom plugin for CC technical blog.

- content/community/code-of-conduct/enforcement/contents.lr
Removed a stray parenthesis in the e-mail link for conduct@creativecommons.org which was leading to a 404 error page when clicked at http://creativecommons.github.io/community/code-of-conduct/enforcement/
**Checklist:**
index.md`).
Version 1.1
Suite D4700 …
> Fixed e-mail link

- content/community/contents.lr
An update of Slack channel names as gsoc 2019 has finished.
> update slack channel names

- README.md
- content/cc-fonts/contents.lr
- content/cc-vue-vocabulary/contents.lr
Since two other repos, [Vue Vocabulary](https://github.com/creativecommons/vue-vocabulary) and [Fonts](https://github.com/creativecommons/fonts) are using, or planning to use, a Netlify-based CI/CD pipeline, it would be useful to have redirects for them as well from the Open Source at CC site.
This is useful as we can pursue publishing the links as subdirectories of the **opensource.creativecommons.org** domain name which is more semantic compared to a **.netlify.com** subdomain.
index.md`).
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
> Add two more redirects for other Netlify based repos

- content/internships/intern-guide/contents.lr
Includes link to blog posts tagged "Outreachy" and "GSOC" to the Intern Guide.
Fix markup to correctly link to CC technical blog
index.md`).
```
Version 1.1
Suite D4700 …
```
> Add link to intern guide and fix markup link

- content/contributing-code/contents.lr
This link takes advantage of the GH search syntax by using the `-` operator. By adding `-label:"in progress"`, we filter out everything with that label.
index.md`).
```
Version 1.1
Suite D4700
indicated in the file; …
```
> Add "help wanted" issues link that filters out "in progress" issues to contributing page

- content/internships/project-ideas-collection/legal-database/contents.lr
Fixes #190 
Updated broken links to correctly point to https://cc-vocabulary.netlify.com/.
index.md`).
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
```
> Fixed broken links on project ideas page to correctly point at vocabulary site.

- configs/markdown-table.ini
- packages/markdown-table/.gitignore
- packages/markdown-table/README.md
- packages/markdown-table/lektor_markdown_table.py
- packages/markdown-table/setup.py
Fixes #225  by @TimidRobot 
Currently, there are no default styling for markdown tables.
This new Lektor plugin uses the required Bootstrap classes - ```thead-dark``` and ```table table-striped```.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```
> Add default styling for tables

- webpack/package-lock.json
- webpack/package.json
This adds '@creativecommons/vocabulary' to the repo. 
Installed 1.0.0-beta.14 version for the '@creativecommons/vocabulary'.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```
> Add '@creativecommons/vocabulary' to the project

- content/community/contents.lr
Add link to cc-licenses-dev slack channel to the Community page.
> Add link to cc-dev-licenses slack channel

- .github/CODEOWNERS
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Added core committers to codeowners

- content/blog/authors/charini/contents.lr
- content/blog/entries/flickr-sub-provider-retrieval/contents.lr
Related to GSoC 2020-initial blog post
Blog post on Sub-provider retrieval from Flickr
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> GSoC blog post 1 - Flickr Sub-provider Retrieval

- content/blog/authors/blank_profile.svg
- themes/vocabulary_theme/templates/authors.html
- themes/vocabulary_theme/templates/macros/authors.html
- webpack/sass/main.scss
This updates all authors page according to the mockup.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Update all authors page.

- content/vocabulary/contents.lr
We already have a redirect in place for `/cc-vocabulary` but would like an additional for `/vocabulary`.
I _think_ I did this correctly, please review 😸 
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```
> Add `/vocabulary` redirect

- themes/vocabulary_theme/templates/page-with-toc.html
- webpack/sass/main.scss
Fixes #396 
Makes the 'On this page' table of contents sticky. I didn't do the _entire sidebar_ because sticky items that are too tall can mean users can't access some of the lower items.
Also adds a global `.sticky-top` css class that can be used elsewhere.
Note, this does not have any effect on mobile displays.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> Sticky Table of Contents

- webpack/package-lock.json
- webpack/package.json
Updates vocabulary version to the latest version.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> update vocabulary version.

- content/internships/history/contents.lr
The Outreachy rounds on the internship history page did not have the links in the Markdown anchor tags `[](...)`, causing them to appear enclosed in `[ ]`. This is fixed by this PR.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```
> Add the missing links to the Outreachy rounds

- themes/vocabulary_theme/templates/layout.html
We moved the CC Search contribution guide to the CC Search dropdown in https://github.com/creativecommons/creativecommons.github.io-source/pull/474 by @ooyeraju, we don't want it in two places.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole …
```
> Removed CC Search item for contributing section

- content/blog/entries/automate-github-for-more-than-CI CD/contents.lr
Small bugfix removing localhost from a link to our community team in: `/blog/entries/automate-github-for-more-than-CI%20CD/`
<details>
```
Version 1.1
Suite D4700 …
```
> Remove localhost from community team link

- content/contributing-code/github-repo-guidelines/contents.lr
This PR fixes broken links and updates the text to reference the new standard labels incorporated across CC repos.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Update documentation about the new standard labels

- content/contributing-code/contents.lr
Fixes #533 by @dhruvkb 
Changes the old labels to the new ones.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Replace deprecated label with the new label name

- content/contributing-code/contents.lr
Fixes #533  by @dhruvkb 
updated the labels in contribution guidelines. The new label that is applied to all new issues is 🚦 status: awaiting triage.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to …
```
> update the labels in contribution guidelines

- themes/vocabulary_theme/templates/macros/og_image.html
I put double quotes _inside_ of the og image urls 🤦 on blog pages:
example: https://opensource.creativecommons.org/blog/entries/summary-my-gsod-2020-journey/
```
https://cc-og-image.vercel.app/Summary: My GSoD 2020 Journey<br><sm style="font-size:70px;">By Ariessa Norramli</sm>.png?&md=1&fontFamily=roboto-condensed&fontSize=100px&images=https%3A%2F%2Fcc-vocabulary.netlify.app%2Flogos%2Fproducts%2Fopen_source.svg%23opensource&images=https://secure.gravatar.com/avatar/6ee7af2da22737fd49ce56adc226d2cb?size=300&d=mp
```
This PR removes them.
> Update og_image.html to fix quotes

- webpack/js/issue-finder.js
Fixes #585 by @shubhanshu02
The warning `Cannot Find Element: #vue-app` is visible on all pages except the Issue Finder. Vue is trying to render the Issue Finder component from webpack/js/component.js on every page, but since the div with `id="vue-app"` is available only on Issue Finder, the warning is visible.
I changed the condition to check if the `pathname` is `/contributing-code/issue-finder/`. This allows the rendering of the Issue Finder component only on Issue Finder page, not on every page.
index.md`).
<details>
```
Version 1.1
1 …
```
> Conditional Rendering of Issue Finder App

- webpack/package-lock.json
- webpack/package.json
- webpack/webpack.config.js
Update node/npm packages to most recent working versions.
I significantly simplified `package.json` since it is private (will never be published for others to use) and used `jq` to format it (`jq -SM '.' package.json > NEW; mv NEW package.json`)
Warnings before changes:
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated …
```
> Webpack updates

- themes/vocabulary_theme/templates/page-with-toc.html
Fixes #627 by @cuibonobo
Fixes the parent link in the 'Contribution Guidelines' section of the site so that it no longer points to a non-existent page.
The 'Contribution Guidelines' parent link now appears with the correct styles when you are on the 'Contribution Guidelines' page.
index.md`).
<details>
```
Version 1.1
Suite D4700
San …
```
> Fixes parent link in 'Contribution Guidelines' section. Fixes #627

- README.md
- content/internships/project-ideas-collection/add-cc-chooser-wordpress/contents.lr
- content/internships/project-ideas-collection/chooser-stewardship/contents.lr
- content/internships/project-ideas-collection/legal-tools-machine-layer/contents.lr
- models/project-idea.ini
- themes/vocabulary_theme/templates/project-ideas.html
- improve formatting (ex. make it easier to cut & paste commands)
- add size to potential internship projects
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```
> Readme and projects

- content/programs/project-ideas-collection/modernize-termination-of-transfer-wp-plugin/contents.lr
- content/programs/project-ideas-collection/refactor-cc-meta-search/contents.lr
Fixes #670 by @possumbilities 
Corrects the general repository name references in the "Application Tips" section of both CC Meta Search, and Termination of Transfer work programs projects' listings.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies …
```
> correct repository general name references in application tips for Termination of Transfer and CC Meta Search work program projects listings

- content/contents.lr
Fixes #703 by @adidevs
The lists in the Get Involved section of the homepage are not aligned due to longer heading of the "Integrate CC licenses into your project". This PR fixes that by refactoring the content as per the file changes to align the lists.
BEFORE:
AFTER: 
index.md`).
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```
> Fixed alignment of homepage Get Involved list

- content/archives/old-tech-blog/entries/gsoc-cc-wordpress-plugin-weekly-report-4/contents.lr
- themes/vocabulary_theme/templates/layout.html
Fixes #737  by @SoundaryaKoutharapu
I have made span text area to show a message if no email is entered
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Fixed no email in Subscribe input area

- content/contributing-code/github-repo-guidelines/contents.lr
update repo guidelines to include configuration settings and better support organization default community health files
- creativecommons/.github#38
<details>
<summary> 🖼️  Screenshot</summary>
</details>
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
> update repo guidelines

- content/blog/entries/2024-05-28-creativecommons-org/contents.lr
- content/blog/entries/2024-05-29-creativecommons-org/contents.lr
add blog post: New CreativeCommons.org launched 2023 September
<details>
<summary> 🖼️ New CreativeCommons.org launched 2023 September</summary>
</details>
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```
> add blog post: New CreativeCommons.org launched 2023 September

- themes/vocabulary_theme/templates/macros/authors_gravatar.html
- themes/vocabulary_theme/templates/macros/posts.html
- Fixes #684  by @TimidRobot 
move mulit-author image support to macro so it is used everywhere
index.md`).
<details>
```
Version 1.1
Suite D4700
By …
```
> move mulit-author image support to macro so it is used everywhere

- themes/vocabulary_theme/templates/blocks/featured-projects.html
- themes/vocabulary_theme/templates/project_list.html
The fallback URL for **Visit site** would redirect user back to home page when the **website** link doesn't exist.
- Fixes #801  by @naishasinha 
The PR adds an `or` parameter in the Visit site redirect `{{ repo.website or repo.url }}` , that way if the website URL is non-existent it falls back to the github repo URL.
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
> Fix fallback for 'Visit site' link when repo.website is missing 

- content/contents.lr
- themes/vocabulary_theme/templates/blocks/hero.html
- themes/vocabulary_theme/templates/layout.html
- webpack/sass/home-page.scss
- Fixes #793 by @briandominick
This pull request resolves an issue where users might mistakenly visit this site while looking for Creative Commons (CC) licenses/tools, which could lead to confusion about the purpose of the site.
To address this:
- Added a prominent button to the hero section of the homepage labeled "Share your work using our licenses/tools" linking to the Creative Commons Share Your Work page.
- Clarified the site’s purpose by adding a notice near the top of the homepage, informing visitors that this site is for developers contributing to Creative Commons, but anyone can use CC tools to share their work.
* Modified `content/contents.lr` to include the new button and the clarification notice on the homepage.
* Updated `webpack/sass/home-page.scss` to style the new button …
> Add prominent link to CC tools and clarify site purpose (Fixes #793)

- themes/vocabulary_theme/templates/layout.html
- Fixes #755 by @Murdock9803
This pull request removes the outdated Twitter logo from the footer section and updates it with the new X logo, as per the current brand guidelines.
- Removed the old Twitter logo from the footer.
- If necessary, replace it with the new X logo or update the code to leave the section as is (depending on the project requirements).
To verify the changes:
1. Go to [https://opensource.creativecommons.org](https://opensource.creativecommons.org/).
2. Scroll to the footer section.
3. Ensure the **Twitter logo** is no longer visible and the section looks correct without it.
before
after
> Remove twitter logo from footer

- themes/vocabulary_theme/templates/page-with-toc.html
-  Related to
- #858 
- #859
- #861 by @Queen-codes 
This PR refactors the code in `page-with-toc.html` to align with vocabulary markup. 
Now(with old CSS commented out)
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```
> refactored code to align with vocabulary markup

- themes/vocabulary_theme/templates/blog-category.html
- themes/vocabulary_theme/templates/blog-post.html
- themes/vocabulary_theme/templates/blog.html
- themes/vocabulary_theme/templates/macros/categories.html
- themes/vocabulary_theme/templates/macros/pagination.html
- themes/vocabulary_theme/templates/macros/posts.html
- Related to #860 by @Queen-codes 
This PR refactors the blog page and blog posts to match the context and markup provided in vocabulary
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> refactored blog page to align with vocabulary markup

- themes/vocabulary_theme/templates/community_team_list.html
- Related to #858  by @Queen-codes 
This PR refactors the community team page to align with vocabulary specimen for teams
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> refactored community team page to align with vocabulary markup

- models/author.ini
- themes/vocabulary_theme/templates/author.html
- themes/vocabulary_theme/templates/layout.html
- themes/vocabulary_theme/templates/macros/author_posts.html
- themes/vocabulary_theme/templates/macros/posts.html
- Related to #860  by @Queen-codes 
This PR refactors the `author.html` code to match the specimen provided for `person-page.html` in vocabulary
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```
> refactored code to align with vocab markup for person

- assets/static/css/style.css
- themes/vocabulary_theme/templates/layout.html
Browser console error:
```
The stylesheet http://127.0.0.1:5000/assets/static/vocabulary/css/vocabulary.css
was not loaded because its MIME type, “text/html”, is not “text/css”.
```
(`/assets/static/vocabulary/css/vocabulary.css` is HTML because it is a 404 page)
Fix `vocabulary.css` import:
1. `assets/static/css/style.css`: correct `vocabulary.css` path
2.  `themes/vocabulary_theme/templates/layout.html` remove `vocabulary.css` (since it is now successfully included from `style.css`)
index.md`). …
> Fix vocabulary.css import

- webpack/package-lock.json
- Fixes #853 
- 🟡 [Predictable results in nanoid generation when given non-integer values · CVE-2024-55565 · GitHub Advisory Database](https://github.com/advisories/GHSA-mwcw-c2x4-8c55)
Update NPM modules (nanoid@3.3.8, etc.)
```shell
cd webpack
npm list --package-lock-only --all > npmlist.old
git checkout -b npm-updates
npm update
npm list --package-lock-only --all > npmlist.new
diff -u npmlist.old npmlist.new
```
```diff
--- npmlist.old	2025-01-08 07:59:58
+++ npmlist.new	2025-01-08 08:06:56
@@ -1,7 +1,7 @@
webpack@ /Users/timidrobot/git/creativecommons/creativecommons.github.io-source/webpack
├─┬ @babel/core@7.26.0
│ ├─┬ @ampproject/remapping@2.3.0
-│ │ ├─┬ @jridgewell/gen-mapping@0.3.5
+│ │ ├─┬ @jridgewell/gen-mapping@0.3.8
│ │ │ ├── @jridgewell/set-array@1.2.1
│ │ │ …
```
> Update NPM modules (nanoid@3.3.8, etc.)

- assets/static/css/style.css
- content/contents.lr
- models/home.ini
- themes/vocabulary_theme/templates/blocks/get-involved.html
- themes/vocabulary_theme/templates/blocks/hero.html
- themes/vocabulary_theme/templates/blocks/recent-posts.html
- themes/vocabulary_theme/templates/layout.html
- Fixes #855 by @Queen-codes 
- adds styles to the `styles.css` file based on the styling from CC's main website (most of the applicable styles were lifted)
- removes all legacy styling from the  homepage `contents.lr` file
- add's `program-index` styling for get involved and featured projects section.
index.md`).
<details>
```
Version 1.1
1 Letterman …
```
> feat: restyle CC's open source website to match vocab design feel

- assets/static/css/style.css
- themes/vocabulary_theme/templates/project_list.html
- themes/vocabulary_theme/templates/search_roadmap.html
- Fixes #893 by @Queen-codes 
- adds `datatable display` class to the table
- adds a `div` with class `content body-container` for local styling
- styles featured project section
index.md`).
<details>
```
Version 1.1
Suite D4700
license …
```
> restyled project list page

- themes/vocabulary_theme/templates/blog.html
- Fixes #918 by @Queen-codes 
this pr addresses the issue of author images being large and removes the featured class to allow all posts be equal grids.
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```
> removed featured class to remove blog highlight

- Pipfile.lock
- Fixes #932 
- 🟡 [Jinja2 vulnerable to sandbox breakout through attr filter selecting format method · CVE-2025-27516 · GitHub Advisory Database](https://github.com/advisories/GHSA-cpwx-vrp4-4pq7)
- Fixes #790
Update Python modules
```shell
pipenv run pip list > piplist.old
git checkout -b update-python
pipenv update --dev
pipenv run pip list > piplist.new
gsed -e'/^---/d' -i piplist.*
diff -u piplist.old piplist.new
```
(`gsed` is GNU Sed installed via Homebrew. The binary name may simply be `sed` on your system, if you use GNU/Linux.)
```diff
--- piplist.old	2025-05-13 15:10:04
+++ piplist.new	2025-05-13 15:10:04
@@ -1,36 +1,36 @@
Package            Version
-babel              2.16.0
-black              24.10.0
+babel              2.17.0
+black              25.1.0 …
```
> Update Python modules

- themes/vocabulary_theme/templates/blog-category.html
- themes/vocabulary_theme/templates/page-with-toc.html
Remove `filter-menu` class from side navigation (collapse spacing between menu items from 2 em to 1 em)
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Remove filter-menu class from side navigation

- assets/static/css/style.css
- assets/static/vocabulary/css/vocabulary.css
- Fixes #943  by @possumbilities 
Fixes sidebar visual distinction issue on contributing pages by adding background styling and improved spacing to match the design consistency used in legal tools pages.
- Added `var(--vocabulary-brand-color-soft-gold)` background color to sidebar container
- Applied consistent `1em` padding and `4.1rem` left margin for proper spacing  
- Set `height: fit-content` to ensure sidebar scales appropriately with content
- Removed excessive `padding-left: 4.1em` that was causing layout issues
- **Fixed link visibility by removing white underline background that was masking text on gold background**
1. Navigate to any Contributing Code page (e.g., `/contributing-code/`)
2. Verify sidebar now has a light gold background that clearly separates it from main content …
> Fix sidebar visual distinction on contributing-code page
